version: '3.8'

services:
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api_service:
      image: q2
      container_name: api_service
      restart: on-failure
      ports: 
          - 8000:80
      depends_on: 
        - rabbitmq

  sale_creation_service:
      image: q
      container_name: sale_creation_service
      restart: on-failure
      ports: 
          - 8001:80
      depends_on: 
        - rabbitmq